import { pool } from "../config/database.js";
import { isValidId } from "../helpers/validation.js";
import { getCurrentUserId } from "../helpers/currentUser.js";
import { getOwnedTrip } from "../helpers/tripOwnership.js";

//autogenerated list of packing items for a trip
const DEFAULT_PACKING_ITEMS = [
  "Passport",
  "Phone charger",
  "Medications",
  "Travel adapter",
  "Toothbrush & toothpaste",
  "Deodorant",
  "Reusable water bottle",
];

const getOwnedPackingList = async (packingListId, userId) => {
  const { rows } = await pool.query(
    `SELECT packing_list.*
     FROM packing_list
     JOIN trips ON packing_list.trip_id = trips.id
     WHERE packing_list.id = $1 AND trips.user_id = $2`,
    [packingListId, userId],
  );
  return rows[0] ?? null;
};

// GET /api/trips/:tripId/packing-list: placeholder query, adjust columns/table once the packing list schema is finalized
const getAllPackingListItems = async (req, res) => {
  const {tripId} = req.params;
  if (!isValidId(tripId)) return res.status(400).json({ error: "Trip ID is required" });

  try {
    const userId = await getCurrentUserId();
    if (!userId) return res.status(404).json({ error: "User not found" });

    const trip = await getOwnedTrip(tripId, userId);
    if (!trip) return res.status(404).json({ error: "Trip not found" });
    
    const { rows } = await pool.query(
      `SELECT * FROM packing_list 
      WHERE trip_id = $1`,
      [tripId]
    );
    res.json(rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// GET /api/packing-list/:id - Retrieve a specific packing list item by its ID
const getPackingListItemById = async (req, res) => {
  const { id } = req.params;
  if (!isValidId(id)) return res.status(400).json({ error: "Invalid packing list item id" });

  try {
    const userId = await getCurrentUserId();
    if (!userId) return res.status(404).json({ error: "User not found" });

    const packingList = await getOwnedPackingList(id, userId);
    if (!packingList) return res.status(404).json({ error: "Packing list item not found" });
    res.json(packingList);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// POST /api/trips/:tripId/packing-items/generate
const generatePackingItems = async (req, res) => {
  const { tripId } = req.params;

  try {
    const userId = await getCurrentUserId();
    if (!userId) return res.status(404).json({ error: "User not found" });

    const trip = await getOwnedTrip(tripId, userId);
    if (!trip) return res.status(404).json({ error: "Trip not found" });
    
    for (const item of DEFAULT_PACKING_ITEMS) {
      await pool.query(
        `INSERT INTO packing_list
          (trip_id, name, is_packed, is_auto_generated)
         VALUES ($1, $2, $3, $4)`,
        [tripId, item, false, true]
      );
    }
    res.status(201).json({ message: "Default packing items generated successfully" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// POST /api/trips/:tripId/packing-list
const createPackingListItem = async (req, res) => {
  const { tripId } = req.params;
  const { name } = req.body;

  if (!name || !name.trim()) { return res.status(400).json({ error: "Name is required" });} 
  
  try {
    const userId = await getCurrentUserId();
    if (!userId) return res.status(404).json({ error: "User not found" });

    const trip = await getOwnedTrip(tripId, userId);
    if (!trip) return res.status(404).json({ error: "Trip not found" });
    
    const { rows } = await pool.query(
      `INSERT INTO packing_list (trip_id, name, is_packed, is_auto_generated) 
      VALUES ($1, $2, $3, $4) 
      RETURNING *`,
      [tripId, name.trim(), false, false]
    );
    res.status(201).json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// PATCH /api/packing-list/:id - Update an existing packing list item
const updatePackingListItem = async (req, res) => {
  const { id } = req.params;
  const { name, is_packed} = req.body;

  //try catch statement where we will update item in table, with characteristics of name, is_packed, is_auto_generated
  try {
    const userId = await getCurrentUserId();
    if (!userId) return res.status(404).json({ error: "User not found" });

    const packingList = await getOwnedPackingList(id, userId);
    if (!packingList) return res.status(404).json({ error: "Packing list item not found" });

    const {rows} = await pool.query (
      `UPDATE packing_list 
        SET name = COALESCE($1, name), 
        is_packed = COALESCE($2, is_packed)
      WHERE id = $3
      RETURNING *`, 
      [name, is_packed, id]
    );

    if (!rows.length) return res.status(404).json({ error: "Packing list item not found" });
    res.json(rows[0]);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

// DELETE /api/packing-list/:id - Delete a packing list item
const deletePackingListItem = async (req, res) => {
  const { id } = req.params;
  if (!isValidId(id)) return res.status(400).json({ error: "Invalid packing list item id" });

  try{
    const userId = await getCurrentUserId();
    if (!userId) return res.status(404).json({ error: "User not found" });

    const packingList = await getOwnedPackingList(id, userId);
    if (!packingList) return res.status(404).json({ error: "Packing list item not found" });

    const {rows} = await pool.query ( `DELETE FROM packing_list WHERE id = $1`, [id] );
    
    res.status(204).send(); 
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
};

export {
  getOwnedPackingList,
  getAllPackingListItems,
  getPackingListItemById,
  generatePackingItems,
  createPackingListItem,
  updatePackingListItem,
  deletePackingListItem,
};
